#page title
page_title                                : EsportsStream - Live Gaming Action                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : EsportsStream                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Discover and watch live esports streams with real-time browsing and seamless video streaming.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Charles Inze Soussol                                
your_link                                 :                     
your_city                                 :                                
email_address                             : contact@esportsstream.app
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : charlesinzesoussol
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Live Stream Discovery
    description                           : Browse and discover live esports streams in real-time with advanced search and filtering capabilities.
    fontawesome_icon_name                 : search
    
  - title                                 : Seamless Video Streaming
    description                           : Watch high-quality esports streams with optimized video playback and minimal buffering.
    fontawesome_icon_name                 : play-circle

  - title                                 : Real-time Search
    description                           : Find streams by game, creator, or title with instant search results and live filtering.
    fontawesome_icon_name                 : bolt

  - title                                 : Gaming-Focused UI
    description                           : Dark theme optimized for gaming with gaming green accents and mobile-first design.
    fontawesome_icon_name                 : gamepad

  - title                                 : User Authentication
    description                           : Secure login and profile management with industry-standard authentication.
    fontawesome_icon_name                 : user-shield
  
  - title                                 : Mobile Optimized
    description                           : Native mobile experience built with React Native and Expo for iOS and Android.
    fontawesome_icon_name                 : mobile-alt

  - title                                 : Pull-to-Refresh
    description                           : Stay updated with the latest streams using intuitive pull-to-refresh functionality.
    fontawesome_icon_name                 : sync-alt

  - title                                 : Stream Categories
    description                           : Browse streams by popular esports games including League of Legends, CS2, Valorant, and more.
    fontawesome_icon_name                 : th-large

  - title                                 : Live Status Indicators
    description                           : See real-time viewer counts and live status indicators for all active streams.
    fontawesome_icon_name                 : circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#0a0a0a"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#0a0a0a"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#1a1a1a"

link_color                                : "#00ff88"

app_title_color                           : "#ffffff"
app_price_color                           : "#00ff88"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#cccccc"

feature_icons_foreground_color            : "#00ff88"
feature_icons_background_color            : "#2a2a2a"

social_icons_foreground_color             : "#cccccc"
social_icons_background_color             : "#2a2a2a"

footer_text_color                         : "#cccccc"




####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor
  - _site
  - .bundle
  - .sass-cache
  - node_modules
  - .expo
  - .expo-shared
  - expo-env.d.ts
  - babel.config.js
  - metro.config.js
  - tsconfig.json
  - package.json
  - package-lock.json
  - __tests__
  - "*.test.*"
  - "*.spec.*"

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown